<a href="https://colab.research.google.com/github/Jonata-Garcia/Prova_Estrutura_de_Dados_e_Analise_de_Algoritimos/blob/main/Jonata_Pablo_Garcia_ipybn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Questão 1**: Listas
# Utilize o Python para criar uma função chamada filtrar_numeros (lista) que:

**A-)** (1,0 ponto) receba uma lista de números inteiros;

**B-)** (1,0 ponto) retorne uma nova lista apenas com os números ímpares
positivos;

**C-)** (1,0 ponto) exiba o maior número da lista resultante.

**D-)** (1,0 ponto) explique o que acontece se a lista estiver vazia.

**RESPOSTA:** Se ela estiver vazia é porque não há nenhum número ímpar positivo para ser exibido. Nesse caso, a função não consegue calcular o maior número, porque o Python não permite usar a função max() em uma lista vazia isso geraria um erro.
Por isso, antes de tentar encontrar o maior valor, a função faz uma **verificação:** Se a lista filtrada estiver vazia, ela mostra uma mensagem informando que não há números ímpares positivos. Assim, o programa continua funcionando normalmente, sem interrupções.

**E-)** (1,0 ponto) teste a função com: dados = [10, -3, 5, 0, 11, -7, 8, 3, 15]

In [ ]:
def filtrar_numeros(lista):

    if not isinstance(lista, list):
        raise TypeError("O parâmetro deve ser uma lista.")

    for elemento in lista:
        if not isinstance(elemento, int):
            raise ValueError("Todos os elementos da lista devem ser inteiros.")

    impares_positivos = [num for num in lista if num > 0 and num % 2 != 0]

    if impares_positivos:
        maior_numero = max(impares_positivos)
        print(f"Questão C: o maior número da lista resultante é {maior_numero}")
    else:
        print("A lista resultante está vazia. Nenhum número ímpar positivo encontrado.")
    return impares_positivos


dados = [10, -3, 5, 0, 11, -7, 8, 3, 15]
resultado = filtrar_numeros(dados)

print("Lista resultante:", resultado)


Questão C: o maior número da lista resultante é 15
Lista resultante: [5, 11, 3, 15]


# **Questão 2**: Vetores
# Dado o vetor: v = np.array([3, 7, 2, 9, 4, 10]). Calcule:

**A-)** (1,0 ponto) média dos valores;

**B-)** (1,0 ponto) elemento de maior valor e seu índice;

**C-)** (1,0 ponto) soma dos elementos maiores que a média.

**D-)** (1,0 ponto) crie um novo vetor com os elementos de v em ordem crescente e
mostre o resultado.

**E-)** (1,0 ponto) explique por que o acesso direto aos índices de um vetor é mais
eficiente que o acesso em listas encadeadas.

**RESPOSTA:** O acesso direto aos índices de um vetor é mais eficiente porque, em um vetor, os elementos são armazenados de forma contígua na memória. Isso significa que o computador consegue calcular rapidamente o endereço de qualquer elemento a partir do índice, resultando em um tempo de acesso constante (O(1)).

Já nas listas encadeadas, os elementos não ficam em posições contíguas, cada nó armazena um valor e uma referência (ou ponteiro) para o próximo. Assim, para acessar um elemento específico, é necessário percorrer a lista a partir do início até o índice desejado, o que torna o tempo de acesso proporcional ao tamanho da lista (O(n)).

In [1]:
import numpy as np

v = np.array([3, 7, 2, 9, 4, 10])

media = np.mean(v)
print("a) Média dos valores:", media)

maior_valor = np.max(v)
indice_maior = np.argmax(v)
print("b) Maior valor:", maior_valor, " | Índice:", indice_maior)

soma_maiores_media = np.sum(v[v > media])
print("c) Soma dos elementos maiores que a média:", soma_maiores_media)

v_ordenado = np.sort(v)
print("d) Vetor em ordem crescente:", v_ordenado)


a) Média dos valores: 5.833333333333333
b) Maior valor: 10  | Índice: 5
c) Soma dos elementos maiores que a média: 26
d) Vetor em ordem crescente: [ 2  3  4  7  9 10]


# **Questão 3**: Matrizes
# use numpy.random.randint() Crie um programa que gere uma matriz 4x4 de números inteiros aleatórios entre 1 e 9. Em seguida:

**A-)** (1,0 ponto) calcule a soma dos elementos da diagonal principal;

**B-)** (1,0 ponto) crie uma nova matriz contendo apenas os elementos maiores
que 5, substituindo os demais por zero.

**C-)** (1,0 ponto) Calcule a soma de todos os elementos pares da matriz original;

**D-)** (1,0 ponto) Calcule a média dos elementos de cada linha e armazene o
resultado em um vetor (array unidimensional).

**E-)** (1,0 ponto) explique a diferença entre array 2D e lista de listas no Python.

**RESPOSTA:** Um array 2D do NumPy e uma lista de listas em Python possuem diferenças estruturais e de desempenho.
O array 2D é uma estrutura homogênea e contígua na memória, o que permite operações matemáticas
vetorizadas e alto desempenho, pois o NumPy é implementado em C. Já a lista de listas é uma
estrutura nativa do Python, mais flexível, mas menos eficiente, pois cada sublista pode ter
tamanhos diferentes e os elementos não ficam armazenados de forma contígua na memória.
Assim, arrays são mais adequados para cálculos numéricos e processamento de dados, enquanto
listas de listas são mais indicadas para estruturas heterogêneas ou de propósito geral.

In [2]:
import numpy as np

matriz = np.random.randint(1, 10, size=(4, 4))
print("Matriz gerada:\n", matriz)

soma_diagonal = np.trace(matriz)
print("\nA) Soma da diagonal principal:", soma_diagonal)

matriz_maiores_5 = np.where(matriz > 5, matriz, 0)
print("\nB) Matriz com elementos > 5 (outros = 0):\n", matriz_maiores_5)

soma_pares = np.sum(matriz[matriz % 2 == 0])
print("\nC) Soma dos elementos pares:", soma_pares)

media_linhas = np.mean(matriz, axis=1)
print("\nD) Média de cada linha:", media_linhas)



Matriz gerada:
 [[7 5 3 5]
 [7 4 8 7]
 [5 9 2 4]
 [3 2 6 7]]

A) Soma da diagonal principal: 20

B) Matriz com elementos > 5 (outros = 0):
 [[7 0 0 0]
 [7 0 8 7]
 [0 9 0 0]
 [0 0 6 7]]

C) Soma dos elementos pares: 26

D) Média de cada linha: [5.  6.5 5.  4.5]


# **Questão 4**: Álgebra Linear- Autovalores e Autovetores
# import numpy as np use np.linalg.eig(A) Considere a matriz quadrada: A = np.array([[4, 2], [1, 3]])

**A-)** (1,0 ponto) calcule os autovalores e autovetores de A.

**RESPOSTA:**
Autovalores (λ): [5. 2.]
Autovetores (colunas de P):
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

**B-)** (1,0 ponto) verifique se a relação A @ v = λ * v é válida para cada par (λ, v).

**RESPOSTA:**
  Para λ = 5.00, diferença = [0. 0.]
  Para λ = 2.00, diferença = [2.22044605e-16 2.22044605e-16]
Relação válida (diferenças próximas de zero).


**C-)** (1,0 ponto) interprete o significado geométrico dos autovetores.

**RESPOSTA:** Os autovetores indicam direções que permanecem inalteradas pela transformação linear de A;
nessas direções, o vetor é apenas esticado ou comprimido pelo fator λ correspondente.

**D-)** (1,0 ponto) calcule o determinante e o traço de A e relacione com os
autovalores.

**RESPOSTA:** Determinante de A = 10.000000000000002
Traço de A = 7.0
Soma dos autovalores = 7.0
Produto dos autovalores = 10.0
Portanto, tr(A) = soma dos autovalores e det(A) = produto dos autovalores.


**E-)** (1,0 ponto) mostre como A pode ser reescrita na forma A = PDP ^
−1 ,indicando as matrizes P e D.

**RESPOSTA:**  
[[ 0.89442719 -0.70710678]

 [ 0.4472136   0.70710678]]

Matriz D (diagonal de autovalores):

 [[5. 0.]

 [0. 2.]]

Matriz P^-1:

 [[ 0.74535599  0.74535599]

 [-0.47140452  0.94280904]]

Verificação A = P D P^-1¹:

 [[4. 2.]

 [1. 3.]]

Diferença entre A e P D P^-1¹:

 [[-8.8817842e-16  0.0000000e+00]

 [-4.4408921e-16  4.4408921e-16]]

In [4]:
import numpy as np

A = np.array([[4, 2],
              [1, 3]], dtype=float)

eigenvals, eigenvecs = np.linalg.eig(A)

verificacoes = [A @ eigenvecs[:, i] - eigenvals[i] * eigenvecs[:, i] for i in range(len(eigenvals))]

det_A = np.linalg.det(A)
trace_A = np.trace(A)

P = eigenvecs
D = np.diag(eigenvals)
P_inv = np.linalg.inv(P)
A_recon = P @ D @ P_inv

# **Questão 5**: Vetor
# Faça um programa que leia um vetor de 6 posições para números reais e, depois, um código inteiro. Se o código for zero, finalize o programa; se for 1, mostre o vetor na ordem direta; se for 2, mostre o vetor na ordem inversa. Caso o código for diferente de 1 e 2, escreva uma mensagem informando que o código é inválido.

In [6]:
vetor = []
for i in range(6):
    valor = float(input(f"Digite o {i+1}º número real: "))
    vetor.append(valor)

codigo = int(input("\nDigite o código (0 = sair, 1 = ordem direta, 2 = ordem inversa): "))

if codigo == 0:
    print("\nPrograma finalizado.")

elif codigo == 1:
    print("\nVetor na ordem direta:")
    print(vetor)

elif codigo == 2:
    print("\nVetor na ordem inversa:")
    print(vetor[::-1])

else:
    print("\nCódigo inválido! Digite apenas 0, 1 ou 2.")


Digite o 1º número real: 2.5
Digite o 2º número real: 3.7
Digite o 3º número real: 1.0
Digite o 4º número real: 9.8
Digite o 5º número real: 4.2
Digite o 6º número real: 7.5

Digite o código (0 = sair, 1 = ordem direta, 2 = ordem inversa): 2

Vetor na ordem inversa:
[7.5, 4.2, 9.8, 1.0, 3.7, 2.5]


# **Questão 6**: Matriz

# Faça um programa para gerar automaticamente números entre 0 e 99 de uma cartela de bingo. Sabendo que cada cartela deverá conter 5 linhas de 5 números, gere estes dados de modo a não ter números repetidos dentro das cartelas. O programa deve exibir na tela a cartela gerada.

In [7]:
import numpy as np

numeros = np.random.choice(range(100), size=25, replace=False)

cartela = numeros.reshape((5, 5))

print("===== CARTELA DE BINGO =====")
for linha in cartela:
    for numero in linha:
        print(f"{numero:02d}", end="  ")
    print()

===== CARTELA DE BINGO =====
65  98  30  29  27  
56  52  10  02  23  
24  62  53  15  31  
13  11  99  69  71  
43  81  50  94  77  
